In [2]:
import numpy as np

In [3]:
# Array criado a partir de uma lista Python
arr1 = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [4]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [5]:
type(arr1)

# tipo ndarray = qualquer numero de dimensoes

numpy.ndarray

In [6]:
# Verificando o formato do array. Que seria a quantidade de dimensoes do array
arr1.shape

# Shape explicado na imagem abaixo

(9,)

![DSA](imagens/formatos.png)

### Imprimindo elementos de acordo com o seu indice

In [7]:
arr1[4]

np.int64(48)

In [8]:
arr1[1:4]

array([21, 32, 43])

In [9]:
indices = [1, 2, 5, 6]

arr1[indices]

array([21, 32, 15, 76])

### Criando uma mascara para que seja retornado somente valores que são pares


In [10]:
mask = (arr1 % 2 == 0)

mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [11]:
arr1[mask]

array([10, 32, 48, 76])

### Alterando um elemento de um array

In [12]:
arr1[0] = 11

In [13]:
arr1[0]

np.int64(11)

### Array de outros tipos

In [18]:
arr1 = np.array([True, False, False, True])

arr1.dtype

dtype('bool')

In [19]:
arr1 = np.array(['Abacaxi', 'Laranja', 'Mamao'])

arr1.dtype

dtype('<U7')