In [2]:
import numpy as np

In [4]:
arr2 = np.array([1, 2, 3, 4, 5])

arr2

array([1, 2, 3, 4, 5])

In [5]:
type(arr2)

numpy.ndarray

In [7]:
# Soma o indice atual com todos os indices anteriores

arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [9]:
# Multiplica o indice atual com todos os indices anteriores

arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [10]:
arr3 = np.arange(0, 50, 5)

arr3

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [11]:
np.shape(arr3)

(10,)

In [13]:
arr3.dtype

dtype('int64')

In [16]:
# Cria um array de ZEROS

arr4 = np.zeros(10)

arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# Faz a diagonal principal na matriz

arr5 = np.eye(3)

arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Faz a diagonal principal na matriz, usando na diagonal numeros da minha escolha

arr6 = np.diag(np.array([1, 2, 1, 2]))

arr6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 2]])