In [1]:
import numpy as np

In [4]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [13]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(2, 3)

In [8]:
# Função para criar uma matriz com os valores 1

arr2 = np.ones((2,3))

arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
lista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

# A função matrix cria uma matriz a partir de uma lista de listas
arr3 = np.matrix(lista)

In [10]:
arr3.shape

(3, 3)

In [15]:
type(arr3)

numpy.matrix

In [16]:
arr3.size

9

In [19]:
arr3

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [18]:
# Indexação da matriz
arr3[2,1]

np.int64(48)

In [22]:
# Indexação da matriz
arr3[0:2,2]

# Todos os elementos que estejam entre as linhas 0 e 1, da coluna 2

matrix([[22],
        [59]])

In [23]:
# Indexação da matriz
arr3[1,]

# Retorna todas as colunas da linha 1

matrix([[ 0, 34, 59]])

In [25]:
# Alterando um elemento da matriz
arr3[1,0] = 100

In [26]:
arr3

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [27]:
x = np.array([1, 2])  # NumPy decide o tipo dos dado
y = np.array([1.0, 2.0])  # NumPy decide o tipo dos dado
z = np.array([1, 2], dtype = np.float64)  # Forçamos um tipo de dado em particular

In [28]:
print(x.dtype, y.dtype, z.dtype)

int64 float64 float64


In [29]:
arr4 = np.array([[24, 76, 92, 14], [47, 35, 89, 2]], dtype = float)

In [30]:
arr4

array([[24., 76., 92., 14.],
       [47., 35., 89.,  2.]])

In [32]:
# O itemsize de um array numpy é um atributo que retorna o tamanho em bytes de cada elemento do array. 
# Em outras palavras, o itemsize representa o número de bytes necessários para armazenar cada valor do array numpy.

arr4.itemsize

8

In [33]:
# Quantidade de bytes ocupado por todo o array no computador

arr4.nbytes

64