In [1]:
import numpy as np

In [3]:
arr15 = np.arange(1, 10)

arr15

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sum(arr15)

np.int64(45)

In [5]:
np.prod(arr15)

np.int64(362880)

In [6]:
## Soma acumulada de todos os elementos

np.cumsum(arr15)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

### Somando 2 array

In [7]:
arr16 = np.array([3, 2, 1])
arr17 = np.array([1, 2, 3])

# Soma dos arrays
arr18 = np.add(arr16, arr17)  

arr18

array([4, 4, 4])

### Multiplicando 2 array

In [8]:
# Cria duas matrizes
arr19 = np.array([[1, 2], [3, 4]])
arr20 = np.array([[5, 6], [0, 7]])

# Multiplicar as duas matrizes
arr21 = np.dot(arr19, arr20)

arr21

# O numero de colunas da primeira matriz tem que ser o mesmo numero de linhas da segunda matriz

array([[ 5, 20],
       [15, 46]])

![DSA](imagens/dot.png)

In [11]:
# Multiplicar as duas matrizes
arr21 = arr19 @ arr20

arr21

array([[ 5, 20],
       [15, 46]])