In [1]:
import numpy as np

In [3]:
arr22 = np.diag(np.arange(3))

arr22

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [4]:
# Retorna um unico elemento

arr22[1, 1]

np.int64(1)

In [5]:
# Retorna somente uma linha

arr22[1]

array([0, 1, 0])

In [6]:
# Retorna somente uma coluna

arr22[:,2]

array([0, 0, 2])

In [7]:
arr23 = np.arange(10)

arr23

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# [start:end:step]

# Quero os itens do indice 2 ao 9 saltanto de 3 em 3

arr23[2:9:3]

array([2, 5, 8])

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

# Comparação item a item
a == b

array([False,  True, False,  True])

In [11]:
# Comparação global
np.array_equal(arr22, arr23)

False

In [12]:
# Somando um valor a cada elemento do array
np.array([1, 2, 3]) + 1.5

array([2.5, 3.5, 4.5])

In [13]:
arr24 = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

arr24

array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [15]:
# Usando o método around
arr25 = np.around(arr24)

arr25

array([1., 2., 2., 2., 4., 4.])

In [16]:
arr26 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr26

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
# "Achatando" a matriz
arr27 = arr26.flatten()

arr27

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
arr28 = np.array([1, 2, 3])

arr28

array([1, 2, 3])

In [19]:
# Repetindo os elementos de um array
np.repeat(arr28, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [21]:
# Repetindo os elementos de um array
np.tile(arr28, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
arr29 = np.array([5, 6])

# Criando cópia do array
arr30 = np.copy(arr29)

arr30

array([5, 6])